name: "ci"

on:
  pull_request:
    branches:
      - "main"
  workflow_dispatch:
    
jobs:
  Spec:
    uses: "puppetlabs/cat-github-actions/.github/workflows/module_ci.yml@object_test"
    with:
      runs_on: "ubuntu-24.04"
    secrets: "inherit"

  Acceptance:
    needs: Spec
    uses: "puppetlabs/cat-github-actions/.github/workflows/module_acceptance.yml@object_test"
    with:
      flags: '--latest-agent'
    secrets: "inherit"
