name: "Test on Ubuntu Github Runners"

on: [push, pull_request]

jobs:
  Acceptance:
    strategy:
      fail-fast: false
      matrix:
        platform:
          - ubuntu-16.04
          - ubuntu-18.04
          - ubuntu-20.04
        collection:
          - puppet5
          - puppet6
          - puppet7-nightly
        exclude:
          # newer OS not supported on older agent
          - platform: ubuntu-20.04
            collection: puppet5

    runs-on: ${{ matrix.platform }}

    steps:
      - name: Checkout Source
        uses: actions/checkout@v2

      - name: Activate Ruby 2.7
        uses: actions/setup-ruby@v1
        with:
          ruby-version: "2.7"

      - name: Cache gems
        uses: actions/cache@v2
        with:
          path: vendor/gems
          key: ${{ runner.os }}-pr-${{ hashFiles('**/Gemfile') }}
          restore-keys: |
            ${{ runner.os }}-pr-
            ${{ runner.os }}-

      - name: Prepare inventory file
        run: |
          cat <<EOF >> inventory.yaml
          ---
          version: 2
          groups:
          - name: local
            targets:
            - uri: litmus_localhost
              config:
                transport: local
          - name: ssh_nodes
            targets: []
          - name: winrm_nodes
            targets: []
          EOF

      - name: Install gems and puppet agent
        run: |
          bundle install
          sudo -u root env "PATH=$PATH" bundle exec rake 'litmus:install_agent[${{ matrix.collection }}]'

      - name: Install module
        run: bundle exec rake 'litmus:install_module'

      - name: Run acceptance tests
        run: sudo -u root env "PATH=$PATH" bundle exec rake 'litmus:acceptance:localhost'
